### ISSUE TITLE
Logo proposal for EPOLLO

### ISSUE THREAD

**Issue by ggabogarcia** [MartinKondor/epollo#2]
Hi, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by MartinKondor** [comment]
That would be awesome! Go ahead :)

**Comment by ggabogarcia** [comment]
Great! +1:

**Comment by ggabogarcia** [comment]
Hello @MartinKondor , here are my logo proposals for Epollo. My proposals are based on union and continuity as Epollo presents, we can read, write and continue a story. Tell me which one you like, and if you want some change.

![epollo2](https://user-images.githubusercontent.com/35750428/40620755-931090f2-625f-11e8-8e65-7dd315d94b91.png)

**Comment by MartinKondor** [comment]
I like all of them, but my favorite is the first one. Can you make the first one's font style a bit more modern?
Not the same but something like [this](https://images.g2crowd.com/uploads/product/hd_favicon/1487566661/express-js.png).

**Comment by ggabogarcia** [comment]
Of course. :)

**Comment by ggabogarcia** [comment]
Check [this](https://i.imgur.com/RErMNMb.png) . :)

**Comment by ggabogarcia** [comment]
I believe that the fusion of the letters with the logo is great in the proposal 2, but it could be given more thickness to the letter so that it has more strength. Checks [this](https://i.imgur.com/4sxpT3W.png) and [this](https://i.imgur.com/LAir2AM.png) .

**Comment by MartinKondor** [comment]
Okay, that will be the logo. :)
Nice work! 
What is next, you commit or you send me an email? How about the license, where I can declare that this logo is your work?

**Comment by ggabogarcia** [comment]
Thank you very much :). I will organize the files and send them by
G-drive Tell me the different sizes in which you need the logo.

**Comment by ggabogarcia** [comment]
![derechos](https://user-images.githubusercontent.com/35750428/40395535-2ca369e0-5dee-11e8-9824-4fdb575c50f1.jpg)

This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/#)

**Comment by MartinKondor** [comment]
Okay, well maybe the sizes could be:

- 370/250
- 720/500
- 1200/720

Of course not exactly these sizes, because I don't want the text to be deformed. Just be close to these sizes.

I will attach the license next to the logo. But GPL and CC is not compatible, the site cannot use CC licensed things, what if you change the license to GPL or MIT, and then the Copyright notice would remain?

**Comment by MartinKondor** [comment]
Nevermind about what I said on license now I read: 
```
No additional restrictions
```

**Comment by MartinKondor** [comment]
If you are done, send me the link in email: [martinkondor@gmail.com](mailto://martinkondor@gmail.com).

**Comment by ggabogarcia** [comment]
Excellent :)

**Comment by MartinKondor** [comment]
Thanks for your work, I think it’s completly professional.:)
Tell me If you have sended it.

**Comment by ggabogarcia** [comment]
Ready sent :)

**Comment by MartinKondor** [comment]
Okay, amazing, really, I love that work!
I will upload it tomorrow (it’s 11pm in Hungary). Thanks!! :)

**Comment by ggabogarcia** [comment]
You're welcome, it was a pleasure to work with you, thank you very much :)
